### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by TheOfficialMrRoboto** [afrojezus/yura#7]
I tried to start the script and I get the following:
```
Failed to compile.

./src/index.js
Module not found: Can't resolve './config' in  '/home/yura/src'
```

**Comment by afrojezus** [comment]
you need a config.js file to make it run with anilist (which provides anime info for it), just setup an account on anilist and head over to [the developer settings](https://anilist.co/settings/developer/) to get the `client_id` and `client_secret` creds to make it run

**Comment by TheOfficialMrRoboto** [comment]
Can you send me the config file format?

**Comment by afrojezus** [comment]
`module.exports = {
          client_id: '',
          client_secret: ''
}`

ctrl-v this into a file called `config.js` inside the `src` folder

**Comment by TheOfficialMrRoboto** [comment]
Thanks

**Comment by TheOfficialMrRoboto** [comment]
Quick question, I've never used eslint and I was wondering how to get rid of all the warnings

**Comment by afrojezus** [comment]
just got to follow what the warnings say by removing and adjusting, ill clean up the code in a later time
